Admin page functionality
NybergViktor/Celemo_FrontEnd pull request #97
Opened 2024-05-20 14:06 UTC by TommyDahlin

Added so you can ban and unban users, also see users roles.

You also get a prompt to confirm you want to ban someone.

2024-05-20 18:05 UTC, NybergViktor commented
# lagt till några funktioner, alla är testade och fungerar.

- Bannade användare hamnar i en egen kategori.
- Man kan se alla användare.
- Man kan söka efter en användare.
- Man kan ban/unban användare med hjälp av id.

2024-05-20 18:06 UTC, NybergViktor commented
![Screenshot 2024-05-20 at 20 03 37](https://github.com/NybergViktor/Celemo_FrontEnd/assets/144717637/c32b2519-ccda-4ec1-83a8-cee6718b2229)
![Screenshot 2024-05-20 at 20 03 47](https://github.com/NybergViktor/Celemo_FrontEnd/assets/144717637/b67bbdd1-6238-48bd-afc6-723a184752ac)
![Screenshot 2024-05-20 at 20 03 56](https://github.com/NybergViktor/Celemo_FrontEnd/assets/144717637/f9dc35c6-a5ce-4996-81cc-c0c54bd2e686)
![Screenshot 2024-05-20 at 20 04 00](https://github.com/NybergViktor/Celemo_FrontEnd/assets/144717637/2b47959f-1314-4aea-82ea-dcf9dfbc3f02)

2024-05-20 18:35 UTC, NybergViktor commented
Bytte till vit bakgrund, såg finare ut.

![Screenshot 2024-05-20 at 20 35 25](https://github.com/NybergViktor/Celemo_FrontEnd/assets/144717637/bf60fa70-3a85-4006-964d-300c30a31ca9)

2024-05-21 07:41 UTC, johnsson84 requested changes
Everything works except the last function to ban user by ID
![image](https://github.com/NybergViktor/Celemo_FrontEnd/assets/69533976/0eb4602e-7223-4ea9-ab89-bc06dac05e6b)

2024-05-21 08:49 UTC, NybergViktor commented
the last function to ban user by ID now works

2024-05-21 09:09 UTC, johnsson84 approved these changes
Works good!

2024-05-21 09:42 UTC, merged